version: '3.0'
services:
  haste-server:
    build: .
    #networks:
    #- db-network
    environment:
      - STORAGE_TYPE=file
      - STORAGE_HOST=localhost
        #- STORAGE_PORT=11211
    ports:
      - 7777:7777
        #  memcached:
        #image: memcached:latest
        #networks:
        #- db-network
    volumes:
      - /home/chchang/git/haste-server/data:/usr/src/app/data

